### ISSUE TITLE
'sform' info stripped from output skull-stripped images

### ISSUE THREAD

**Issue by beaudsy** [MIC-DKFZ/HD-BET#10]
Hi Fabian,
  Great program!  Thank you for sharing!

  I have been using HD-BET for past few months to skull-strip T1 images, but am now coming up against an "Inconsistent orientation" error using FSL's make_bianca_mask.  I linked this to the sform information being stripped from the nifti header in the HD-BET created skull-stripped image (using skull-stripped image from FSL bet which does not remove sform info works perfectly with make_bianca_mask without issue).

I am wondering why HD-BET strips this info and whether there may be plans to prevent this from happening or adding the info back into the output images. 

Thanks.

Andrew

**Comment by FabianIsensee** [comment]
Hi, oh wow I must have overlooked this issue somehow. This problem is related to SimpleITK which HD-BET uses. You should be able to just overwrite the geometry of the resulting segmentations with that of the original image and everything should be fine.
Best,
Fabian

**Comment by beaudsy** [comment]
Fabian,
  Absolutely no problem.  Found a work-a-round similar to the one you recommended.  Appreciate the reply.

Andrew
