### ISSUE TITLE
default parameter download folder inconsistent

### ISSUE THREAD

**Issue by function2-llx** [MIC-DKFZ/HD-BET#15]
Hello, it seems that the default parameter download folder is inconsistent between that in readme(`~/.hd-bet_params`) and that in `HD-BET/paths.py`(`~/hd-bet_params`). A single dot is the difference, maybe a typo.

**Comment by FabianIsensee** [comment]
Hi,
indeed that is a typo which should be fixed. Thanks for pointing this out!
Best,
Fabian
