### ISSUE TITLE
GPU not recognized?

### ISSUE THREAD

**Issue by keithcdodd** [MIC-DKFZ/HD-BET#16]
I use a Dell XPS 13 9300 with the GPU: "Intel Corporation Iris Plus Graphics G7 (rev 07)" -- on Ubuntu 20.04. When I try to run HD-BET it gives an error "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx". 

Is there a way to get it to recognize and use my GPU? Or does it have to be NVIDIA based? 

I understand I can use my CPU, and plan on using that if the GPU cannot work, but I wanted to check!

Thanks!

**Comment by FabianIsensee** [comment]
Hi, HD-GLIO uses pytorch and pytorch needs an Nvidia GPU. You can specify that you want to run the prediction on CPU though. This will be slow but it works.
Best,
Fabian

**Comment by keithcdodd** [comment]
Ah, gotcha. Makes sense, just too bad. I really appreciate that it can also run on CPU!

Thanks for the fast reply and help!

**Comment by FabianIsensee** [comment]
Unfortunately nothing we can do about it :-)
