### ISSUE TITLE
Can I get a pretrained weight?

### ISSUE THREAD

**Issue by han-yeol** [MIC-DKFZ/HD-BET#19]
Hi 
I am impressed with your work. 
Thank you very much. 

As you know, training code is not available.
so, Can I get a pretrained weight?

I look forward to your reply.
Regards.

**Comment by Alxaline** [comment]
In the code `utils.py` there is the link where the weights are downloaded :

[Fold 0](https://zenodo.org/record/2540695/files/0.model?download=1)
[Fold 1](https://zenodo.org/record/2540695/files/1.model?download=1)
[Fold 2](https://zenodo.org/record/2540695/files/2.model?download=1)
[Fold 3](https://zenodo.org/record/2540695/files/3.model?download=1)
[Fold 4](https://zenodo.org/record/2540695/files/4.model?download=1)

Best regards,

**Comment by FabianIsensee** [comment]
Thanks @Alxaline
