### ISSUE TITLE
How to train HD-bet on new data?

### ISSUE THREAD

**Issue by zeydabadi** [MIC-DKFZ/HD-BET#2]
Hi,
I was able to use the HD-bet on our data. The pros are it is fast (on a Tesla P100 GPU) and fully automatic but the results were not exactly better than a semi-automatic modified FSL/BET.
I wonder whether I can somehow train the model on our data and improve the outputs?

Thanks,
Mahmoud

**Comment by FabianIsensee** [comment]
Hi Mahmoud,
would it be possible to share one of the datasets it did not work on? I would like to see what is going on. Also what do you mean by 'not exactly better than XXX'? Does hd-bet give very large errors in the segmentation output or is it just the border of the brain that is not hit precisely?
Best,
Fabian

**Comment by FabianIsensee** [comment]
What kind of data is it you are working on? T1 MRI? Does your data have tumours or other pathologies?
best,
Fabian

**Comment by zeydabadi** [comment]
Hi Fabian,

Unfortunately, I am not allowed to share the data and it needs a lot of paperwork to get permission.
The data are from infants around 3 months old. Both T1-MPRAGE and T2-SPACE.
The results for T2-SPACE are almost perfect but for T1-MPRAGE is not as good. 
I don't have a qualitative measure not but just by eyeballing and comparing with the FSL/BET's output it seems that HD-bet segments parts of the anatomy that is not the brain, most noticeably around the neck and eyeballs. All images contain neck and parts of the shoulder as the infants are tiny.

Thanks,
Mahmoud

**Comment by FabianIsensee** [comment]
Hi Mahmoud,
that is quite the domain shift. Please note that the focus of hd-bet is 1) the robustness with respect to pathologies and 2) the capability of running on a variety of MRI sequences. We did not train our models on any other than adult patients. I would expect there to be some performance drops when moving to infants. It should also be noted that our training images did not contain anything below the neck, so if there are shoulders in the images then there could be segmentation errors.
It is interesting that T2 works better than T1 for your data given that in our data hd-bet on T2 typically performed the worst in comparison.
To get back to your original question, I am afraid we cannot share the code for training the model. It is not in a state where it would be usable by others. What you could do, however, is use the network architecture and plug it into your own training.
When you are saying it segments "parts of the anatomy that is not the brain", how large are these false positives? If that's possible, you could also send me a screenshot to f.isensee@dkfz.de (but only if that's OK with your data usage policies!).
Best,
Fabian
