### ISSUE TITLE
unable to download 2.model.

### ISSUE THREAD

**Issue by xNeorem** [MIC-DKFZ/HD-BET#29]
Running hd-bet -i INPUT_FILENAME the execution freezes when trying to download "2.model". 
I tried to download it by following the link but the download stops at 26mb.

**Comment by athenacet** [comment]
I also have a similar issue. Running hd-bet -i INPUT_FILENAME the execution ends with some errors like HTTP error 502,503 or 504. I am using google colab.

**Comment by athenacet** [comment]
I also have a similar issue. Running hd-bet -i INPUT_FILENAME the execution ends with some errors like HTTP error 502,503 or 504. I am using google colab.

**Comment by keat123** [comment]
I also have a similar issue. Running hd-bet -i INPUT_FILENAME the execution ends with some errors like HTTP error 502,503 or 504. I am using google colab.

**Comment by xNeorem** [comment]
I am using colab too, I resolved using wget to download all of 4 models. 
You can get the model's link by console log.

**Comment by keat123** [comment]
Can you please share the command lines for that
