### ISSUE TITLE
Cannot run postprocessing because the postprocessing file is missing

### ISSUE THREAD

**Issue by ZubicarayG** [MIC-DKFZ/HD-BET#41]
Hello,

I'm encountering this issue with HD-BM:

WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the
output folder of the model first!
The folder you need to run this in is /home/dezubica/NeuroAI-HD/HD-BM/normal

The folder 'normal' contains only the following files: fold_0 fold_1 fold_2 fold_3 fold_4 plans.pkl

**Comment by FabianIsensee** [comment]
This is just a warning, you can safely ignore it
Best,
Fabian
