### ISSUE TITLE
Issue with mkl-service 

### ISSUE THREAD

**Issue by DaDsoul** [MIC-DKFZ/HD-BET#9]
When I try to run the hd-bet command, the following issue is showed, I tried to fix with setting MKL_THREADING parameter but did not help much. Any suggestions?

Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-7c85b1e2.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.

**Comment by FabianIsensee** [comment]
It looks like your MKL installation is not compatible with hd-bet. I have never seen this and don't know how to resolve this. Have you tried googling the error?
Can you please try installing hd-bet in a python virtual environment `virtualenv -p python3 hd_bet_venv && hd_bet_venv/bin/activate` -> then install hd-bet?

**Comment by DaDsoul** [comment]
Oh, fixed it. Just did as you said. Thanks!

**Comment by saruarlive** [comment]
It solved my problem

```
import os
os.environ['MKL_THREADING_LAYER'] = 'GNU'

```
